version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: Install codeclimate
          command: sudo npm install -g codeclimate-test-reporter
      - run:
          name: Install node dependencies
          command: npm install
      - run:
          name: Run test
          command: npm test
      - run:
          name: Run code coverage report
          command: npm run cover
      - run:
          name: Checking build
          command: |
            ls -agolf dist/
            codeclimate-test-reporter < coverage/lcov.info

  deploy:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the USWDS package
          command: npm run build
      - run:
          name: Publish to NPM
          command: |
            npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
            npm publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
